workflows:
  ios-capacitor:
    name: List iOS Schemes
    environment:
      xcode: latest
    scripts:
      - name: List schemes in workspace
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -list